# Site settings
title: WanderCosta
header-img: img/home-bg-coffee.jpg
email: contact@wandercosta.com
description: "This is my personal blog, where I post my thougths about technology, software developement, and whatever I find interesting!"
baseurl: ""
url: "http://www.wandercosta.com"
comments: true

# Social
twitter_username: rwanderc
github_username: rwanderc
#facebook_username: rwanderc
linkedin_username: rwander
analytics_id: UA-70100612-2
gravatar_url: "https://en.gravatar.com/userimage/65982695/7e0f8f987bd6fc9024e1afc83c70cf4f.png?size=150"

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "vendor"]
permalink: "/:title/"
paginate_path: "/pagina-:num"
paginate: 5
timezone: America/Sao_Paulo

gems: [
  "jekyll-paginate",
  "jemoji"
]

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  input: GFM
  syntax_highlighter: rouge
