# Site settings
title: WanderCosta
header-img: img/home-bg-bridge.jpg
email: contact@wandercosta.com
description: "co-founder of @wideping | software engineer at @FreeNow_DE<br><b>sharing thoughts and pieces of code</b>"
baseurl: ""
url: "http://www.wandercosta.com"
comments: true

# Social
twitter_username: rwanderc
github_username: rwanderc
linkedin_username: rwanderc
analytics_id: UA-70100612-2
gravatar_url: "https://en.gravatar.com/userimage/65982695/50d3c7658867ed21b0c34750042b21b2.jpg?size=200"

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md", "vendor"]
permalink: "/:title/"
paginate_path: "/page-:num"
paginate: 12
timezone: America/Sao_Paulo

excerpt_separator: <!--more-->

gems: [
  "jekyll-paginate",
  "jemoji"
]

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  input: GFM
  syntax_highlighter: rouge
